"""user bio avatar email_verified

Revision ID: 32835af17128
Revises: cd2b72111012
Create Date: 2026-04-26 09:34:37.219994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '32835af17128'
down_revision: Union[str, None] = 'cd2b72111012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'bio',
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
            server_default='',
        ),
    )
    op.add_column(
        'users',
        sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        'users',
        sa.Column(
            'email_verified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
