"""add user_block table

Revision ID: c8dcd64c0c24
Revises: 42d5f8ddc7ed
Create Date: 2026-04-25 16:17:56.276004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c8dcd64c0c24'
down_revision: Union[str, None] = '42d5f8ddc7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_block',
    sa.Column('blocker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_index(op.f('ix_user_block_blocked_id'), 'user_block', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_user_block_blocker_id'), 'user_block', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_block_blocker_id'), table_name='user_block')
    op.drop_index(op.f('ix_user_block_blocked_id'), table_name='user_block')
    op.drop_table('user_block')
    # ### end Alembic commands ###
