"""add device_token table

Revision ID: cd2b72111012
Revises: c8dcd64c0c24
Create Date: 2026-04-25 16:45:06.727502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'cd2b72111012'
down_revision: Union[str, None] = 'c8dcd64c0c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_token',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_device_token_platform'), 'device_token', ['platform'], unique=False)
    op.create_index(op.f('ix_device_token_user_id'), 'device_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_token_user_id'), table_name='device_token')
    op.drop_index(op.f('ix_device_token_platform'), table_name='device_token')
    op.drop_table('device_token')
    # ### end Alembic commands ###
